### ISSUE TITLE
No scroll reset when retry-ing

### ISSUE THREAD

**Issue by justlucdewit** [Vyctor661/king-typer#9]
When you are done typing, you get the graph that shows you how well you did. If you then press the "try again" button, the scroll position of the text box will not reset. which causes it to look like your looking at the first few words, while actually you are looking in the middle of the generated text.

If you then start typing it will suddenly  reset to the start of the textbox and say you did it wrong. Leading to alot of confusion and frustration

**Comment by vycdev** [comment]
Hmm, I tested it on google chrome and it worked just fine, I guess I had to test it on other browsers as well, ok I am gonna fix that when I can.

**Comment by vycdev** [comment]
Fixed the bug. Tested by @maoitsme in firefox. Fix is currently release in the develop branch [9c45175 ](https://github.com/Vyctor661/king-typer/commit/d591aaf7a21e140383729a5ef494e54b371f0db6) and it will be included in the next release.
